package model;
// Generated 08/11/2018 14:48:11 by Hibernate Tools 4.3.1



/**
 * Anamnese generated by hbm2java
 */
public class Anamnese  implements java.io.Serializable {

     private int avaliacaoFisicaId;
     private Avaliacaofisica avaliacaofisica;
     private String resp1;
     private String resp2;
     private String resp3;
     private String resp4;
     private String resp5;
     private String resp6;
     private String resp7;
     private String resp8;
     private String resp9;
     private String resp10;

    public Anamnese() {
    }

	
    public Anamnese(Avaliacaofisica avaliacaofisica) {
        this.avaliacaofisica = avaliacaofisica;
    }
    public Anamnese(Avaliacaofisica avaliacaofisica, String resp1, String resp2, String resp3,
            String resp4, String resp5, String resp6, String resp7, String resp8, String resp9, String resp10) {
        
       this.avaliacaofisica = avaliacaofisica;
       this.resp1 = resp1;
       this.resp2 = resp2;
       this.resp3 = resp3;
       this.resp4 = resp4;
       this.resp5 = resp5;
       this.resp6 = resp6;
       this.resp7 = resp7;
       this.resp8 = resp8;
       this.resp9 = resp9;
       this.resp10 = resp10;
    }
   
    public int getAvaliacaoFisicaId() {
        return this.avaliacaoFisicaId;
    }
    
    public void setAvaliacaoFisicaId(int avaliacaoFisicaId) {
        this.avaliacaoFisicaId = avaliacaoFisicaId;
    }
    public Avaliacaofisica getAvaliacaofisica() {
        return this.avaliacaofisica;
    }
    
    public void setAvaliacaofisica(Avaliacaofisica avaliacaofisica) {
        this.avaliacaofisica = avaliacaofisica;
    }
    public String getResp1() {
        return this.resp1;
    }
    
    public void setResp1(String resp1) {
        this.resp1 = resp1;
    }
    public String getResp2() {
        return this.resp2;
    }
    
    public void setResp2(String resp2) {
        this.resp2 = resp2;
    }
    public String getResp3() {
        return this.resp3;
    }
    
    public void setResp3(String resp3) {
        this.resp3 = resp3;
    }
    public String getResp4() {
        return this.resp4;
    }
    
    public void setResp4(String resp4) {
        this.resp4 = resp4;
    }
    public String getResp5() {
        return this.resp5;
    }
    
    public void setResp5(String resp5) {
        this.resp5 = resp5;
    }
    public String getResp6() {
        return this.resp6;
    }
    
    public void setResp6(String resp6) {
        this.resp6 = resp6;
    }
    public String getResp7() {
        return this.resp7;
    }
    
    public void setResp7(String resp7) {
        this.resp7 = resp7;
    }
    public String getResp8() {
        return this.resp8;
    }
    
    public void setResp8(String resp8) {
        this.resp8 = resp8;
    }
    public String getResp9() {
        return this.resp9;
    }
    
    public void setResp9(String resp9) {
        this.resp9 = resp9;
    }
    public String getResp10() {
        return this.resp10;
    }
    
    public void setResp10(String resp10) {
        this.resp10 = resp10;
    }




}


