package model;
// Generated 08/11/2018 14:48:11 by Hibernate Tools 4.3.1


import java.text.DateFormat;
import java.util.Date;

/**
 * Avaliacaofisica generated by hbm2java
 */
public class Avaliacaofisica  implements java.io.Serializable {


     private Integer id;
     private Aluno aluno;
     private Professor professor;
     private String laudo;
     private Date data;
     private Anamnese anamnese;
     private Perimetria perimetria;
     private Parq parq;
     private DobraCutanea dobraCutanea;
     private Imc imc;

    public Avaliacaofisica() {
    }

	
    public Avaliacaofisica(Aluno aluno, Professor professor, Date data) {
        this.aluno = aluno;
        this.professor = professor;
        this.data = data;
    }
    public Avaliacaofisica(Aluno aluno, Professor professor, String laudo, Date data, Anamnese anamnese, Perimetria perimetria, Parq parq, DobraCutanea dobraCutanea, Imc imc) {
       this.aluno = aluno;
       this.professor = professor;
       this.laudo = laudo;
       this.data = data;
       this.anamnese = anamnese;
       this.perimetria = perimetria;
       this.parq = parq;
       this.dobraCutanea = dobraCutanea;
       this.imc = imc;
    }
    
    
    
    //PARA AJUDAR A MONTAR AS LINHAS DA TABELA NO INTERNALFRAE
     public String[] montarLinha(){
        
        //PEGA A DATA DE NASCIMENTO E RETORNA NO PADRÃO DO PC
        String data = DateFormat.getDateInstance().format(getData());
        
        String[] resp = {getId().toString(),
                        "Aval. #"+getId().toString(),
                        getAluno().getPessoafisica().getPessoa().getNome(),
                        data,
                        getProfessor().getPessoafisica().getPessoa().getNome()};
        
        return resp;
    }
    
    
    
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Aluno getAluno() {
        return this.aluno;
    }
    
    public void setAluno(Aluno aluno) {
        this.aluno = aluno;
    }
    public Professor getProfessor() {
        return this.professor;
    }
    
    public void setProfessor(Professor professor) {
        this.professor = professor;
    }
    public String getLaudo() {
        return this.laudo;
    }
    
    public void setLaudo(String laudo) {
        this.laudo = laudo;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public Anamnese getAnamnese() {
        return this.anamnese;
    }
    
    public void setAnamnese(Anamnese anamnese) {
        this.anamnese = anamnese;
    }
    public Perimetria getPerimetria() {
        return this.perimetria;
    }
    
    public void setPerimetria(Perimetria perimetria) {
        this.perimetria = perimetria;
    }
    public Parq getParq() {
        return this.parq;
    }
    
    public void setParq(Parq parq) {
        this.parq = parq;
    }
    public DobraCutanea getDobraCutanea() {
        return this.dobraCutanea;
    }
    
    public void setDobraCutanea(DobraCutanea dobraCutanea) {
        this.dobraCutanea = dobraCutanea;
    }
    public Imc getImc() {
        return this.imc;
    }
    
    public void setImc(Imc imc) {
        this.imc = imc;
    }




}


