package model;
// Generated 08/11/2018 14:48:11 by Hibernate Tools 4.3.1



/**
 * Biometria generated by hbm2java
 */
public class Biometria  implements java.io.Serializable {


     private Integer id;
     private Pessoafisica pessoafisica;
     private String dedo;
     private byte[] digital;

    public Biometria() {
    }

	
    public Biometria(Pessoafisica pessoafisica) {
        this.pessoafisica = pessoafisica;
    }
    public Biometria(Pessoafisica pessoafisica, String dedo, byte[] digital) {
       this.pessoafisica = pessoafisica;
       this.dedo = dedo;
       this.digital = digital;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Pessoafisica getPessoafisica() {
        return this.pessoafisica;
    }
    
    public void setPessoafisica(Pessoafisica pessoafisica) {
        this.pessoafisica = pessoafisica;
    }
    public String getDedo() {
        return this.dedo;
    }
    
    public void setDedo(String dedo) {
        this.dedo = dedo;
    }
    public byte[] getDigital() {
        return this.digital;
    }
    
    public void setDigital(byte[] digital) {
        this.digital = digital;
    }




}


