package model;
// Generated 08/11/2018 14:48:11 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Caixa generated by hbm2java
 */
public class Caixa  implements java.io.Serializable {


     private Integer id;
     private Empresa empresa;
     private BigDecimal capitalInicial;
     private Set receitas = new HashSet(0);
     private Set despesas = new HashSet(0);

    public Caixa() {
    }

	
    public Caixa(Empresa empresa, BigDecimal capitalInicial) {
        this.empresa = empresa;
        this.capitalInicial = capitalInicial;
    }
    public Caixa(Empresa empresa, BigDecimal capitalInicial, Set receitas, Set despesas) {
       this.empresa = empresa;
       this.capitalInicial = capitalInicial;
       this.receitas = receitas;
       this.despesas = despesas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public BigDecimal getCapitalInicial() {
        return this.capitalInicial;
    }
    
    public void setCapitalInicial(BigDecimal capitalInicial) {
        this.capitalInicial = capitalInicial;
    }
    public Set getReceitas() {
        return this.receitas;
    }
    
    public void setReceitas(Set receitas) {
        this.receitas = receitas;
    }
    public Set getDespesas() {
        return this.despesas;
    }
    
    public void setDespesas(Set despesas) {
        this.despesas = despesas;
    }




}


