package model;
// Generated 08/11/2018 14:48:11 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cidade generated by hbm2java
 */
public class Cidade  implements java.io.Serializable {


     private Integer id;
     private Estado estado;
     private String nome;
     private Set enderecos = new HashSet(0);

     
     //PARA AJUDAR A MONTAR AS LINHAS DA TABELA
     public String[] montarLinha(){
        
        String[] resp = {getId().toString(),getNome(), getEstado().getSigla()};
        
        return resp;  
    }
     
     
     
     
     
     
    public Cidade() {
    }

	
    public Cidade(Estado estado, String nome) {
        this.estado = estado;
        this.nome = nome;
    }
    public Cidade(Estado estado, String nome, Set enderecos) {
       this.estado = estado;
       this.nome = nome;
       this.enderecos = enderecos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set getEnderecos() {
        return this.enderecos;
    }
    
    public void setEnderecos(Set enderecos) {
        this.enderecos = enderecos;
    }




}


