package model;
// Generated 08/11/2018 14:48:11 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * ContaPagar generated by hbm2java
 */
public class ContaPagar  implements java.io.Serializable {


     private Integer id;
     private Empresa empresa;
     private String tipo;
     private Date dataVencimento;
     private BigDecimal valor;
     private String descricao;

    public ContaPagar() {
    }

	
    public ContaPagar(Empresa empresa, String tipo, Date dataVencimento, BigDecimal valor) {
        this.empresa = empresa;
        this.tipo = tipo;
        this.dataVencimento = dataVencimento;
        this.valor = valor;
    }
    public ContaPagar(Empresa empresa, String tipo, Date dataVencimento, BigDecimal valor, String descricao) {
       this.empresa = empresa;
       this.tipo = tipo;
       this.dataVencimento = dataVencimento;
       this.valor = valor;
       this.descricao = descricao;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Date getDataVencimento() {
        return this.dataVencimento;
    }
    
    public void setDataVencimento(Date dataVencimento) {
        this.dataVencimento = dataVencimento;
    }
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }




}


