package model;
// Generated 08/11/2018 14:48:11 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * DobraCutanea generated by hbm2java
 */
public class DobraCutanea  implements java.io.Serializable {


     private int avaliacaoFisicaId;
     private Avaliacaofisica avaliacaofisica;
     private BigDecimal peitoral;
     private BigDecimal axilarMedia;
     private BigDecimal subescapular;
     private BigDecimal suprailiaca;
     private BigDecimal tricipital;
     private BigDecimal bicipital;
     private BigDecimal abdominal;
     private BigDecimal coxa;
     private BigDecimal geminal;
     private BigDecimal lombar;

    public DobraCutanea() {
    }

	
    public DobraCutanea(Avaliacaofisica avaliacaofisica) {
        this.avaliacaofisica = avaliacaofisica;
    }
    public DobraCutanea(Avaliacaofisica avaliacaofisica, BigDecimal peitoral, BigDecimal axilarMedia, BigDecimal subescapular, BigDecimal suprailiaca, BigDecimal tricipital, BigDecimal bicipital, BigDecimal abdominal, BigDecimal coxa, BigDecimal geminal, BigDecimal lombar) {
       this.avaliacaofisica = avaliacaofisica;
       this.peitoral = peitoral;
       this.axilarMedia = axilarMedia;
       this.subescapular = subescapular;
       this.suprailiaca = suprailiaca;
       this.tricipital = tricipital;
       this.bicipital = bicipital;
       this.abdominal = abdominal;
       this.coxa = coxa;
       this.geminal = geminal;
       this.lombar = lombar;
    }
   
    public int getAvaliacaoFisicaId() {
        return this.avaliacaoFisicaId;
    }
    
    public void setAvaliacaoFisicaId(int avaliacaoFisicaId) {
        this.avaliacaoFisicaId = avaliacaoFisicaId;
    }
    public Avaliacaofisica getAvaliacaofisica() {
        return this.avaliacaofisica;
    }
    
    public void setAvaliacaofisica(Avaliacaofisica avaliacaofisica) {
        this.avaliacaofisica = avaliacaofisica;
    }
    public BigDecimal getPeitoral() {
        return this.peitoral;
    }
    
    public void setPeitoral(BigDecimal peitoral) {
        this.peitoral = peitoral;
    }
    public BigDecimal getAxilarMedia() {
        return this.axilarMedia;
    }
    
    public void setAxilarMedia(BigDecimal axilarMedia) {
        this.axilarMedia = axilarMedia;
    }
    public BigDecimal getSubescapular() {
        return this.subescapular;
    }
    
    public void setSubescapular(BigDecimal subescapular) {
        this.subescapular = subescapular;
    }
    public BigDecimal getSuprailiaca() {
        return this.suprailiaca;
    }
    
    public void setSuprailiaca(BigDecimal suprailiaca) {
        this.suprailiaca = suprailiaca;
    }
    public BigDecimal getTricipital() {
        return this.tricipital;
    }
    
    public void setTricipital(BigDecimal tricipital) {
        this.tricipital = tricipital;
    }
    public BigDecimal getBicipital() {
        return this.bicipital;
    }
    
    public void setBicipital(BigDecimal bicipital) {
        this.bicipital = bicipital;
    }
    public BigDecimal getAbdominal() {
        return this.abdominal;
    }
    
    public void setAbdominal(BigDecimal abdominal) {
        this.abdominal = abdominal;
    }
    public BigDecimal getCoxa() {
        return this.coxa;
    }
    
    public void setCoxa(BigDecimal coxa) {
        this.coxa = coxa;
    }
    public BigDecimal getGeminal() {
        return this.geminal;
    }
    
    public void setGeminal(BigDecimal geminal) {
        this.geminal = geminal;
    }
    public BigDecimal getLombar() {
        return this.lombar;
    }
    
    public void setLombar(BigDecimal lombar) {
        this.lombar = lombar;
    }




}


