package model;
// Generated 08/11/2018 14:48:11 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Empresa generated by hbm2java
 */
public class Empresa  implements java.io.Serializable {


     private int pessoaJuridicaId;
     private Pessoajuridica pessoajuridica;
     private String logotipo;
     private Set caixas = new HashSet(0);
     private Set contaPagars = new HashSet(0);
     private Set contaRecebers = new HashSet(0);

    public Empresa() {
    }

	
    public Empresa(Pessoajuridica pessoajuridica) {
        this.pessoajuridica = pessoajuridica;
    }
    public Empresa(Pessoajuridica pessoajuridica, String logotipo, Set caixas, Set contaPagars, Set contaRecebers) {
       this.pessoajuridica = pessoajuridica;
       this.logotipo = logotipo;
       this.caixas = caixas;
       this.contaPagars = contaPagars;
       this.contaRecebers = contaRecebers;
    }
   
    public int getPessoaJuridicaId() {
        return this.pessoaJuridicaId;
    }
    
    public void setPessoaJuridicaId(int pessoaJuridicaId) {
        this.pessoaJuridicaId = pessoaJuridicaId;
    }
    public Pessoajuridica getPessoajuridica() {
        return this.pessoajuridica;
    }
    
    public void setPessoajuridica(Pessoajuridica pessoajuridica) {
        this.pessoajuridica = pessoajuridica;
    }
    public String getLogotipo() {
        return this.logotipo;
    }
    
    public void setLogotipo(String logotipo) {
        this.logotipo = logotipo;
    }
    public Set getCaixas() {
        return this.caixas;
    }
    
    public void setCaixas(Set caixas) {
        this.caixas = caixas;
    }
    public Set getContaPagars() {
        return this.contaPagars;
    }
    
    public void setContaPagars(Set contaPagars) {
        this.contaPagars = contaPagars;
    }
    public Set getContaRecebers() {
        return this.contaRecebers;
    }
    
    public void setContaRecebers(Set contaRecebers) {
        this.contaRecebers = contaRecebers;
    }




}


