package model;
// Generated 08/11/2018 14:48:11 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Estado generated by hbm2java
 */
public class Estado  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private String sigla;
     private Set cidades = new HashSet(0);

    public Estado() {
    }

	
    public Estado(String nome, String sigla) {
        this.nome = nome;
        this.sigla = sigla;
    }
    public Estado(String nome, String sigla, Set cidades) {
       this.nome = nome;
       this.sigla = sigla;
       this.cidades = cidades;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getSigla() {
        return this.sigla;
    }
    
    public void setSigla(String sigla) {
        this.sigla = sigla;
    }
    public Set getCidades() {
        return this.cidades;
    }
    
    public void setCidades(Set cidades) {
        this.cidades = cidades;
    }




}


