package model;
// Generated 03/11/2019 20:29:31 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Exercicio generated by hbm2java
 */
public class Exercicio  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private String grupoMuscular;
     private String imgDemonstrativa;
     private String observacoes;
     private Set treinos = new HashSet(0);

    public Exercicio() {
    }

	
    public Exercicio(String nome, String grupoMuscular) {
        this.nome = nome;
        this.grupoMuscular = grupoMuscular;
    }
    public Exercicio(String nome, String grupoMuscular, String imgDemonstrativa, String observacoes, Set treinos) {
       this.nome = nome;
       this.grupoMuscular = grupoMuscular;
       this.imgDemonstrativa = imgDemonstrativa;
       this.observacoes = observacoes;
       this.treinos = treinos;
    }
    
    
     //PARA AJUDAR A MONTAR AS LINHAS DA TABELA
    public String[] montarLinha(){
        
        String[] resp = {getId().toString(),getNome(), getGrupoMuscular(), getObservacoes()};
        return resp;  
    }

    public String[] montarLinhaExercicio(){
        
        String[] resp = {getId().toString(),getNome()};
        return resp;  
    }
    
    public String[] montarLinhaGrupoMuscular(){
        
        String[] resp = {getGrupoMuscular()};
        return resp;  
    }
    
    
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getGrupoMuscular() {
        return this.grupoMuscular;
    }
    
    public void setGrupoMuscular(String grupoMuscular) {
        this.grupoMuscular = grupoMuscular;
    }
    public String getImgDemonstrativa() {
        return this.imgDemonstrativa;
    }
    
    public void setImgDemonstrativa(String imgDemonstrativa) {
        this.imgDemonstrativa = imgDemonstrativa;
    }
    public String getObservacoes() {
        return this.observacoes;
    }
    
    public void setObservacoes(String observacoes) {
        this.observacoes = observacoes;
    }
    public Set getTreinos() {
        return this.treinos;
    }
    
    public void setTreinos(Set treinos) {
        this.treinos = treinos;
    }




}


