package model;
// Generated 03/11/2019 20:29:31 by Hibernate Tools 4.3.1


import java.text.DateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Fichatreino generated by hbm2java
 */
public class Fichatreino  implements java.io.Serializable {


     private Integer id;
     private Aluno aluno;
     private Professor professor;
     private Date dataInicio;
     private Date validade;
     private String observacoes;
     private Set treinos = new HashSet(0);

    public Fichatreino() {
    }

	
    public Fichatreino(Date dataInicio) {
        this.dataInicio = dataInicio;
    }
    public Fichatreino(Aluno aluno, Professor professor, Date dataInicio, Date validade, String observacoes, Set treinos) {
       this.aluno = aluno;
       this.professor = professor;
       this.dataInicio = dataInicio;
       this.validade = validade;
       this.observacoes = observacoes;
       this.treinos = treinos;
    }
    
    public Fichatreino(Aluno aluno, Professor professor, Date dataInicio, Date validade, String observacoes) {
       this.aluno = aluno;
       this.professor = professor;
       this.dataInicio = dataInicio;
       this.validade = validade;
       this.observacoes = observacoes;
    }
    
    
    public String[] montarLinha(){
        
        //PEGA A DATA DE NASCIMENTO E RETORNA NO PADRÃO DO PC
        String dataValidade = DateFormat.getDateInstance().format(getValidade()),
                inicio = DateFormat.getDateInstance().format(getDataInicio());;
        
        String[] resp = {
            aluno.getPessoafisica().getPessoa().getId().toString(),
            id.toString(),
            aluno.getPessoafisica().getPessoa().getNome(),
            "Ficha #"+id.toString(),
            professor.getPessoafisica().getPessoa().getNome(),
            inicio,
            dataValidade};
        
        return resp;
    }
    
    
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Aluno getAluno() {
        return this.aluno;
    }
    
    public void setAluno(Aluno aluno) {
        this.aluno = aluno;
    }
    public Professor getProfessor() {
        return this.professor;
    }
    
    public void setProfessor(Professor professor) {
        this.professor = professor;
    }
    public Date getDataInicio() {
        return this.dataInicio;
    }
    
    public void setDataInicio(Date dataInicio) {
        this.dataInicio = dataInicio;
    }
    public Date getValidade() {
        return this.validade;
    }
    
    public void setValidade(Date validade) {
        this.validade = validade;
    }
    public String getObservacoes() {
        return this.observacoes;
    }
    
    public void setObservacoes(String observacoes) {
        this.observacoes = observacoes;
    }
    public Set getTreinos() {
        return this.treinos;
    }
    
    public void setTreinos(Set treinos) {
        this.treinos = treinos;
    }




}


