package model;
// Generated 08/11/2018 14:48:11 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Fornecedor generated by hbm2java
 */
public class Fornecedor  implements java.io.Serializable {


     private int pessoaJuridicaId;
     private Pessoajuridica pessoajuridica;
     private String descricao;
     private Set produtos = new HashSet(0);

    public Fornecedor() {
    }

	
    public Fornecedor(Pessoajuridica pessoajuridica) {
        this.pessoajuridica = pessoajuridica;
    }
    public Fornecedor(Pessoajuridica pessoajuridica, String descricao, Set produtos) {
       this.pessoajuridica = pessoajuridica;
       this.descricao = descricao;
       this.produtos = produtos;
    }
   
    public int getPessoaJuridicaId() {
        return this.pessoaJuridicaId;
    }
    
    public void setPessoaJuridicaId(int pessoaJuridicaId) {
        this.pessoaJuridicaId = pessoaJuridicaId;
    }
    public Pessoajuridica getPessoajuridica() {
        return this.pessoajuridica;
    }
    
    public void setPessoajuridica(Pessoajuridica pessoajuridica) {
        this.pessoajuridica = pessoajuridica;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Set getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Set produtos) {
        this.produtos = produtos;
    }




}


