package model;
// Generated 08/11/2018 14:48:11 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Frequencia generated by hbm2java
 */
public class Frequencia  implements java.io.Serializable {


     private Integer id;
     private Aluno aluno;
     private Date data;
     private Date hora;

    public Frequencia() {
    }

    public Frequencia(Aluno aluno, Date data, Date hora) {
       this.aluno = aluno;
       this.data = data;
       this.hora = hora;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Aluno getAluno() {
        return this.aluno;
    }
    
    public void setAluno(Aluno aluno) {
        this.aluno = aluno;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }




}


