package model;
// Generated 08/11/2018 14:48:11 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Funcionario generated by hbm2java
 */
public class Funcionario  implements java.io.Serializable {


     private int pessoaFisicaId;
     private Pessoafisica pessoafisica;
     private String cargo;
     private BigDecimal salario;
     private Date dataContratacao;

    public Funcionario() {
    }

    public Funcionario(Pessoafisica pessoafisica, String cargo, BigDecimal salario, Date dataContratacao) {
       this.pessoafisica = pessoafisica;
       this.cargo = cargo;
       this.salario = salario;
       this.dataContratacao = dataContratacao;
    }
   
    public int getPessoaFisicaId() {
        return this.pessoaFisicaId;
    }
    
    public void setPessoaFisicaId(int pessoaFisicaId) {
        this.pessoaFisicaId = pessoaFisicaId;
    }
    public Pessoafisica getPessoafisica() {
        return this.pessoafisica;
    }
    
    public void setPessoafisica(Pessoafisica pessoafisica) {
        this.pessoafisica = pessoafisica;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }
    public BigDecimal getSalario() {
        return this.salario;
    }
    
    public void setSalario(BigDecimal salario) {
        this.salario = salario;
    }
    public Date getDataContratacao() {
        return this.dataContratacao;
    }
    
    public void setDataContratacao(Date dataContratacao) {
        this.dataContratacao = dataContratacao;
    }




}


