package model;
// Generated 08/11/2018 14:48:11 by Hibernate Tools 4.3.1


import java.text.DateFormat;
import java.util.Date;

/**
 * Horario generated by hbm2java
 */
public class Horario  implements java.io.Serializable {


     private Integer id;
     private Modalidade modalidade;
     private String diaDaSemana;
     private Date horaInicio;
     private Date horaFim;

     
     //montar linha na tabela
     public String[] montarLinha(){
         
        //PEGA A DATA DE NASCIMENTO E RETORNA NO PADRÃO DO PC
        String horaInicio = DateFormat.getTimeInstance().format(getHoraInicio());
        String horaFim = DateFormat.getTimeInstance().format(getHoraFim());
         
         String[] resp= {getDiaDaSemana(),
                         horaInicio,
                         horaFim};
         
         return resp;
     }
     
     
    public Horario() {
    }

    public Horario(Modalidade modalidade, String diaDaSemana, Date horaInicio, Date horaFim) {
       this.modalidade = modalidade;
       this.diaDaSemana = diaDaSemana;
       this.horaInicio = horaInicio;
       this.horaFim = horaFim;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Modalidade getModalidade() {
        return this.modalidade;
    }
    
    public void setModalidade(Modalidade modalidade) {
        this.modalidade = modalidade;
    }
    public String getDiaDaSemana() {
        return this.diaDaSemana;
    }
    
    public void setDiaDaSemana(String diaDaSemana) {
        this.diaDaSemana = diaDaSemana;
    }
    public Date getHoraInicio() {
        return this.horaInicio;
    }
    
    public void setHoraInicio(Date horaInicio) {
        this.horaInicio = horaInicio;
    }
    public Date getHoraFim() {
        return this.horaFim;
    }
    
    public void setHoraFim(Date horaFim) {
        this.horaFim = horaFim;
    }




}


