package model;
// Generated 08/11/2018 14:48:11 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Imc generated by hbm2java
 */
public class Imc  implements java.io.Serializable {


     private int avaliacaoFisicaId;
     private Avaliacaofisica avaliacaofisica;
     private BigDecimal peso;
     private BigDecimal altura;

    public Imc() {
    }

	
    public Imc(Avaliacaofisica avaliacaofisica) {
        this.avaliacaofisica = avaliacaofisica;
    }
    public Imc(Avaliacaofisica avaliacaofisica, BigDecimal peso, BigDecimal altura) {
       this.avaliacaofisica = avaliacaofisica;
       this.peso = peso;
       this.altura = altura;
    }
   
    public int getAvaliacaoFisicaId() {
        return this.avaliacaoFisicaId;
    }
    
    public void setAvaliacaoFisicaId(int avaliacaoFisicaId) {
        this.avaliacaoFisicaId = avaliacaoFisicaId;
    }
    public Avaliacaofisica getAvaliacaofisica() {
        return this.avaliacaofisica;
    }
    
    public void setAvaliacaofisica(Avaliacaofisica avaliacaofisica) {
        this.avaliacaofisica = avaliacaofisica;
    }
    public BigDecimal getPeso() {
        return this.peso;
    }
    
    public void setPeso(BigDecimal peso) {
        this.peso = peso;
    }
    public BigDecimal getAltura() {
        return this.altura;
    }
    
    public void setAltura(BigDecimal altura) {
        this.altura = altura;
    }




}


