package model;
// Generated 08/11/2018 14:48:11 by Hibernate Tools 4.3.1



/**
 * MatriculaId generated by hbm2java
 */
public class MatriculaId  implements java.io.Serializable {


     private int alunoId;
     private int modalidadeId;

    public MatriculaId() {
    }

    public MatriculaId(int alunoId, int modalidadeId) {
       this.alunoId = alunoId;
       this.modalidadeId = modalidadeId;
    }
   
    public int getAlunoId() {
        return this.alunoId;
    }
    
    public void setAlunoId(int alunoId) {
        this.alunoId = alunoId;
    }
    public int getModalidadeId() {
        return this.modalidadeId;
    }
    
    public void setModalidadeId(int modalidadeId) {
        this.modalidadeId = modalidadeId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MatriculaId) ) return false;
		 MatriculaId castOther = ( MatriculaId ) other; 
         
		 return (this.getAlunoId()==castOther.getAlunoId())
 && (this.getModalidadeId()==castOther.getModalidadeId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getAlunoId();
         result = 37 * result + this.getModalidadeId();
         return result;
   }   


}


