package model;
// Generated 08/11/2018 14:48:11 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Matricula generated by hbm2java
 */
public class Matricula  implements java.io.Serializable {


     private MatriculaId id;
     private Aluno aluno;
     private Modalidade modalidade;
     private String status;
     private Date dataMatricula;
     private Set mensalidades = new HashSet(0);

    public Matricula() {
    }
    
    //CONSTRUTOR USADO
     public Matricula(Aluno aluno, Modalidade modalidade, String status, Date dataMatricula) {
       
       this.aluno = aluno;
       this.modalidade = modalidade;
       this.status = status;
       this.dataMatricula = dataMatricula;
      
    }

	
    public Matricula(MatriculaId id, Aluno aluno, Modalidade modalidade) {
        this.id = id;
        this.aluno = aluno;
        this.modalidade = modalidade;
    }
    public Matricula(MatriculaId id, Aluno aluno, Modalidade modalidade, String status, Date dataMatricula, Set mensalidades) {
       this.id = id;
       this.aluno = aluno;
       this.modalidade = modalidade;
       this.status = status;
       this.dataMatricula = dataMatricula;
       this.mensalidades = mensalidades;
    }
   
    public MatriculaId getId() {
        return this.id;
    }
    
    public void setId(MatriculaId id) {
        this.id = id;
    }
    public Aluno getAluno() {
        return this.aluno;
    }
    
    public void setAluno(Aluno aluno) {
        this.aluno = aluno;
    }
    public Modalidade getModalidade() {
        return this.modalidade;
    }
    
    public void setModalidade(Modalidade modalidade) {
        this.modalidade = modalidade;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Date getDataMatricula() {
        return this.dataMatricula;
    }
    
    public void setDataMatricula(Date dataMatricula) {
        this.dataMatricula = dataMatricula;
    }
    public Set getMensalidades() {
        return this.mensalidades;
    }
    
    public void setMensalidades(Set mensalidades) {
        this.mensalidades = mensalidades;
    }




}


