package model;
// Generated 08/11/2018 14:48:11 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Mensalidade generated by hbm2java
 */
public class Mensalidade  implements java.io.Serializable {


     private Integer id;
     private Matricula matricula;
     private Date dataVencimento;
     private Date dataPagamento;
     private BigDecimal desconto;
     private String status;
     private BigDecimal valor;

    public Mensalidade() {
    }

	
    public Mensalidade(Matricula matricula, Date dataVencimento, String status, BigDecimal valor) {
        this.matricula = matricula;
        this.dataVencimento = dataVencimento;
        this.status = status;
        this.valor = valor;
    }
    public Mensalidade(Matricula matricula, Date dataVencimento, Date dataPagamento, BigDecimal desconto, String status, BigDecimal valor) {
       this.matricula = matricula;
       this.dataVencimento = dataVencimento;
       this.dataPagamento = dataPagamento;
       this.desconto = desconto;
       this.status = status;
       this.valor = valor;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Matricula getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(Matricula matricula) {
        this.matricula = matricula;
    }
    public Date getDataVencimento() {
        return this.dataVencimento;
    }
    
    public void setDataVencimento(Date dataVencimento) {
        this.dataVencimento = dataVencimento;
    }
    public Date getDataPagamento() {
        return this.dataPagamento;
    }
    
    public void setDataPagamento(Date dataPagamento) {
        this.dataPagamento = dataPagamento;
    }
    public BigDecimal getDesconto() {
        return this.desconto;
    }
    
    public void setDesconto(BigDecimal desconto) {
        this.desconto = desconto;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }




}


