package model;
// Generated 08/11/2018 14:48:11 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import view.FrmPrincipal;

/**
 * Modalidade generated by hbm2java
 */
public class Modalidade  implements java.io.Serializable {


     private Integer id;
     private String descricao;
     private BigDecimal preco;
     private String plano;
     private byte diaDoVencimento;
     private Short vagas;
     private Set horarios = new HashSet(0);
     private Set matriculas = new HashSet(0);

     //FUNÇÕES
     
     //formatar data
      public static Date  formatarHora(String hora){
     
            SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
            
            /*Calendar h = Calendar.getInstance();
            
            h.set(0, 0, 0,10, 20);
            */
            Date h = null;
            
           
            try {
                 h = sdf.parse("10:20:30");
            
            
            } catch (ParseException ex) {
                Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }

            return h;
     }
     
     //montar linha na tabela
     public String[] montarLinha(){
         String[] resp= {getId().toString(),
                        getDescricao(),
                        getPreco().toString(),
                        String.valueOf(getDiaDoVencimento()),
                        getPlano(),
                        getVagas().toString()};
         
         return resp;
     }
     
     
     //construtor usado
     public Modalidade(String descricao, BigDecimal preco, String plano, byte diaDoVencimento, Short vagas) {
        this.descricao = descricao;
        this.preco = preco;
        this.plano=plano;
        this.diaDoVencimento = diaDoVencimento;
        this.vagas= vagas;
    }
     
     
     
     
    public Modalidade() {
    }

	
    public Modalidade(String descricao, BigDecimal preco, byte diaDoVencimento) {
        this.descricao = descricao;
        this.preco = preco;
        this.diaDoVencimento = diaDoVencimento;
    }
    public Modalidade(String descricao, BigDecimal preco, String plano, byte diaDoVencimento, Short vagas, Set horarios, Set matriculas) {
       this.descricao = descricao;
       this.preco = preco;
       this.plano = plano;
       this.diaDoVencimento = diaDoVencimento;
       this.vagas = vagas;
       this.horarios = horarios;
       this.matriculas = matriculas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public BigDecimal getPreco() {
        return this.preco;
    }
    
    public void setPreco(BigDecimal preco) {
        this.preco = preco;
    }
    public String getPlano() {
        return this.plano;
    }
    
    public void setPlano(String plano) {
        this.plano = plano;
    }
    public byte getDiaDoVencimento() {
        return this.diaDoVencimento;
    }
    
    public void setDiaDoVencimento(byte diaDoVencimento) {
        this.diaDoVencimento = diaDoVencimento;
    }
    public Short getVagas() {
        return this.vagas;
    }
    
    public void setVagas(Short vagas) {
        this.vagas = vagas;
    }
    public Set getHorarios() {
        return this.horarios;
    }
    
    public void setHorarios(Set horarios) {
        this.horarios = horarios;
    }
    public Set getMatriculas() {
        return this.matriculas;
    }
    
    public void setMatriculas(Set matriculas) {
        this.matriculas = matriculas;
    }




}


