package model;
// Generated 08/11/2018 14:48:11 by Hibernate Tools 4.3.1



/**
 * Pessoajuridica generated by hbm2java
 */
public class Pessoajuridica  implements java.io.Serializable {


     private int pessoaId;
     private Pessoa pessoa;
     private String cnpj;
     private String inscricaoEstadual;
     private Fornecedor fornecedor;
     private Empresa empresa;

    public Pessoajuridica() {
    }

	
    public Pessoajuridica(Pessoa pessoa) {
        this.pessoa = pessoa;
    }
    public Pessoajuridica(Pessoa pessoa, String cnpj, String inscricaoEstadual, Fornecedor fornecedor, Empresa empresa) {
       this.pessoa = pessoa;
       this.cnpj = cnpj;
       this.inscricaoEstadual = inscricaoEstadual;
       this.fornecedor = fornecedor;
       this.empresa = empresa;
    }
   
    public int getPessoaId() {
        return this.pessoaId;
    }
    
    public void setPessoaId(int pessoaId) {
        this.pessoaId = pessoaId;
    }
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }
    public String getCnpj() {
        return this.cnpj;
    }
    
    public void setCnpj(String cnpj) {
        this.cnpj = cnpj;
    }
    public String getInscricaoEstadual() {
        return this.inscricaoEstadual;
    }
    
    public void setInscricaoEstadual(String inscricaoEstadual) {
        this.inscricaoEstadual = inscricaoEstadual;
    }
    public Fornecedor getFornecedor() {
        return this.fornecedor;
    }
    
    public void setFornecedor(Fornecedor fornecedor) {
        this.fornecedor = fornecedor;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }




}


