package model;
// Generated 08/11/2018 14:48:11 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pessoa generated by hbm2java
 */
public class Pessoa  implements java.io.Serializable {


     private Integer id;
     private Endereco endereco;
     private String nome;
     private String email;
     private Set telefones = new HashSet(0);
     private Set vendas = new HashSet(0);
     private Pessoafisica pessoafisica;
     private Set contaRecebers = new HashSet(0);
     private Pessoajuridica pessoajuridica;

    public Pessoa() {
    }

    //construtor sendo usado
     public Pessoa(String nome, String email) {
        this.nome = nome;
        this.email=email;
    }
	
    
     
     
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Endereco getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(Endereco endereco) {
        this.endereco = endereco;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getTelefones() {
        return this.telefones;
    }
    
    public void setTelefones(Set telefones) {
        this.telefones = telefones;
    }
    public Set getVendas() {
        return this.vendas;
    }
    
    public void setVendas(Set vendas) {
        this.vendas = vendas;
    }
    public Pessoafisica getPessoafisica() {
        return this.pessoafisica;
    }
    
    public void setPessoafisica(Pessoafisica pessoafisica) {
        this.pessoafisica = pessoafisica;
    }
    public Set getContaRecebers() {
        return this.contaRecebers;
    }
    
    public void setContaRecebers(Set contaRecebers) {
        this.contaRecebers = contaRecebers;
    }
    public Pessoajuridica getPessoajuridica() {
        return this.pessoajuridica;
    }
    
    public void setPessoajuridica(Pessoajuridica pessoajuridica) {
        this.pessoajuridica = pessoajuridica;
    }
}


