package model;
// Generated 08/11/2018 14:48:11 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Receita generated by hbm2java
 */
public class Receita  implements java.io.Serializable {


     private Integer id;
     private Caixa caixa;
     private BigDecimal valor;
     private String tipo;
     private Date data;

    public Receita() {
    }

    public Receita(Caixa caixa, BigDecimal valor, String tipo, Date data) {
       this.caixa = caixa;
       this.valor = valor;
       this.tipo = tipo;
       this.data = data;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Caixa getCaixa() {
        return this.caixa;
    }
    
    public void setCaixa(Caixa caixa) {
        this.caixa = caixa;
    }
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }




}


