package model;
// Generated 08/11/2018 14:48:11 by Hibernate Tools 4.3.1



/**
 * Telefone generated by hbm2java
 */
public class Telefone  implements java.io.Serializable {


     private Integer id;
     private Pessoa pessoa;
     private String numero;
     private String tipo;

    public Telefone() {
    }
    
    public Telefone(String numero, String tipo) {
       this.numero = numero;
       this.tipo = tipo;
    }
   

    public Telefone(Pessoa pessoa, String numero, String tipo) {
       this.pessoa = pessoa;
       this.numero = numero;
       this.tipo = tipo;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }




}


