package model;
// Generated 08/11/2018 14:48:11 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Venda generated by hbm2java
 */
public class Venda  implements java.io.Serializable {


     private Integer id;
     private Pessoa pessoa;
     private Date data;
     private BigDecimal total;
     private int quantidade;
     private String vendedor;
     private String formaPagamento;
     private Set produtos = new HashSet(0);

    public Venda() {
    }

	
    public Venda(Pessoa pessoa, Date data, BigDecimal total, int quantidade) {
        this.pessoa = pessoa;
        this.data = data;
        this.total = total;
        this.quantidade = quantidade;
    }
    public Venda(Pessoa pessoa, Date data, BigDecimal total, int quantidade, String vendedor, String formaPagamento, Set produtos) {
       this.pessoa = pessoa;
       this.data = data;
       this.total = total;
       this.quantidade = quantidade;
       this.vendedor = vendedor;
       this.formaPagamento = formaPagamento;
       this.produtos = produtos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }
    public int getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(int quantidade) {
        this.quantidade = quantidade;
    }
    public String getVendedor() {
        return this.vendedor;
    }
    
    public void setVendedor(String vendedor) {
        this.vendedor = vendedor;
    }
    public String getFormaPagamento() {
        return this.formaPagamento;
    }
    
    public void setFormaPagamento(String formaPagamento) {
        this.formaPagamento = formaPagamento;
    }
    public Set getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Set produtos) {
        this.produtos = produtos;
    }




}


